{{/*
Expand the name of the chart.
*/}}
{{- define "name" -}}
{{- default $.Chart.Name $.Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

#{{/*
#Return instance and name labels.
#*/}}
#{{- define "instance-name" -}}
#app.kubernetes.io/instance: {{ $.Release.Name | quote }}
#app.kubernetes.io/name: {{ include "chart.name" . | quote }}
#{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}


{{/*
Return labels, including instance, name and version.
*/}}
{{- define "labels" -}}
app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
helm.sh/chart: {{ include "chart" . | quote }}
{{- if .globalLabels }}
{{ toYaml .globalLabels }}
{{- end -}}
{{- end -}}

{{/*
Return NodePool labels.
*/}}
{{- define "nodePool.labels" -}}
{{ include "labels" . | indent 8}}
{{- if .labels }}
{{ toYaml .labels | indent 8 }}
{{- end -}}
{{- end -}}

