apiVersion: v2
name: karpenter-nodepool
description: A Helm chart for Karpenter Node pool, it will create the NodePool and the Ec2NodeClass.
type: application
version: 0.0.5
appVersion: 0.0.1
keywords:
  - cluster
  - node
  - autoscaling
home: https://github.com/team-carepay/karpenter-charts
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/team-carepay/karpenter-charts
